# fly.toml app configuration file generated for weathered-sun-9681 on 2023-06-11T10:44:52+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "weathered-sun-9681"
primary_region = "cdg"
console_command = "/rails/bin/rails console"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/rails/frontend/public"
  url_prefix = "/"
